### ISSUE TITLE
Error when upgrading koa-compose to 3.0

### ISSUE THREAD

**Issue by ppascher** [koajs/mount#31]
Hello,

when I update koa-compose to the recently released version 3.0 I keep getting the following error:
```javascript
TypeError: downstream.call(...)[(intermediate value)] is not a function
      at Object.<anonymous> (/projects/intranet_redux/backend/node_modules/koa-mount/index.js:58:23)
      at [object Generator].next (native)
      at Object.<anonymous> (/projects/intranet_redux/backend/node_modules/koa-mount/index.js:60:14)
      at [object Generator].next (native)
      at Object.dispatch (/projects/intranet_redux/backend/node_modules/koa-router/lib/router.js:331:14)
      at [object Generator].next (native)
      at Object.<anonymous> (/projects/intranet_redux/backend/node_modules/koa-mount/index.js:58:23)
      at [object Generator].next (native)
      at Object.serve (/projects/intranet_redux/backend/node_modules/koa-static/index.js:41:14)
      at [object Generator].next (native)
```
I tried looking at the commits from koa-compose since 2.3 but couldn't figure it out.
I currently use it like this
```javascript
// protected route - check if user has a valid token & permissions for ressource
app.use(mount('/api/v1/', compose([jwt({secret: publicKey, algorithm: 'RS256'}), permissionCheck(), apiRoutes.middleware()])));
```

**Comment by derek-duncan** [comment]
I ran into this same error today, but I found a solution I thought you might find useful. First off, the error is occurring because koa-compose 3.0 has been upgraded to koa 2.0. Notably, `ctx` is now being passed as the first argument in middleware vs being referenced with `this`. That's why `.call` is breaking in this case.

I've forked koa-mount and updated the module to work with Koa 2.0. I'm not sure if this should be submitted as a PR, so I'll just link it here. Hope it helps!

[koa-mount for Koa 2.0](https://github.com/derek-duncan/mount)

**Comment by ppascher** [comment]
Thanks alot!
