### ISSUE TITLE
Doesn't work with Koa 2.0

### ISSUE THREAD

**Issue by phaux** [koajs/mount#44]
```js
import 'babel-polyfill'
import Koa from 'koa'
import Router from 'koa-router'
import mount from 'koa-mount'

const api = new Koa
const router = new Router
router.get('/version', async ctx => { ctx.body = {version: '1.0'} })
api.use(router.routes(), router.allowedMethods())

const server = new Koa
server.use(mount('/api', api))

server.listen(8000)
console.log("App running at http://[::]:8000/")
```

```
> koa2-test@0.1.0 start /home/nate/Code/koa2-test
> node lib/start.js

  koa-router defined route HEAD,GET /version +0ms
  koa:application use dispatch +4ms
  koa-mount mount /api unnamed +2ms
koa deprecated Support for generators will been removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x lib/start.js:45:8
  koa:application use - +1ms
  koa:application listen +1ms
App running at http://[::]:8000/
```
After visiting `/api/version`
```
  koa-mount mount /api unnamed -> /version +7s
  koa-mount enter /api/version -> /version +1ms
  koa-router undefined undefined +1ms
  koa-router test /version /^\/version(?:\/(?=$))?$/i +0ms

  TypeError: next is not a function
      at Object.dispatch (/home/nate/Code/koa2-test/node_modules/koa-router/lib/router.js:315:32)
      at Object.<anonymous> (/home/nate/Code/koa2-test/node_modules/koa-mount/node_modules/koa-compose/index.js:25:28)
      at next (native)
      at Object.<anonymous> (/home/nate/Code/koa2-test/node_modules/koa-mount/index.js:58:5)
      at next (native)
      at onFulfilled (/home/nate/Code/koa2-test/node_modules/co/index.js:65:19)
      at /home/nate/Code/koa2-test/node_modules/co/index.js:54:5
      at new Promise (/home/nate/Code/koa2-test/node_modules/core-js/modules/es6.promise.js:193:7)
      at Object.co (/home/nate/Code/koa2-test/node_modules/co/index.js:50:10)
      at converted (/home/nate/Code/koa2-test/node_modules/koa-convert/index.js:17:15)
```

**Comment by coderhaoxin** [comment]
what's your version?

```
npm i koa-mount@next
```

**Comment by phaux** [comment]
My version was 1.3.0. Thank you very much for quick response.
Feel free to close it now, although I think it would be worth to mention the `@next` option in the README

**Comment by coderhaoxin** [comment]
> I think it would be worth to mention the @next option in the README

PR welcome
